name: Unit Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache tool binaries
        uses: actions/cache@v5
        with:
          path: bin
          key: tools-${{ runner.os }}-${{ hashFiles('Makefile') }}

      - name: Run tests
        run: make test-ci
